version: '3.8'

services:
  rtspcapture-garage:
#    image: dsmithson/rtspcameracapture:1.3.514
    build:
      context: .
      dockerfile: src/Dockerfile.Linux
    command: python imageCapture.py
    env_file:
      - secrets.env
    environment:
      - RABBITMQ_EXCHANGE=knightware.cameraImages
      - RABBITMQ_ROUTING_KEY=actions.write.image
      - CAMERA_NAME=garage
      - CAPTURE_INTERVAL_SECONDS=60
      - SSIM_THRESHOLD=0.9
      - RABBITMQ_PORT=5672
